import type {
  Member,
  ClubEvent,
  Perk,
  FaqItem,
  Benefit,
  LevelDef,
  Archetype,
} from "./types";

/* ── Honest founding facts (no inflated numbers) ────────────── */
export const founding = {
  cohortName: "Founding Circle",
  cohortCap: 100,
  launchYear: 2026,
};

/* ── What we're building — membership pillars ───────────────── */
export const benefits: Benefit[] = [
  {
    icon: "Users",
    title: "The Member Directory",
    description:
      "A private directory of every member — who they are, what they're building, and a way to ask for a warm introduction. It grows as the circle does.",
  },
  {
    icon: "UtensilsCrossed",
    title: "Founder Dinners",
    description:
      "Intimate, off-the-record dinners of a handful of founders. No pitching, no panels — the first ones will be small, in the cities where founding members are.",
  },
  {
    icon: "MessagesSquare",
    title: "A Private Room",
    description:
      "A members-only space to think out loud, ask the questions you can't ask publicly, and get honest answers from people who've been there.",
  },
  {
    icon: "Handshake",
    title: "Curated Introductions",
    description:
      "Tell us who you need to meet — a co-investor, a first hire, a customer, a peer in the trenches — and we'll make the introduction by hand.",
  },
  {
    icon: "Tags",
    title: "Member Perks",
    description:
      "Perks on the tools founders actually use. We're lining these up now and will only ever list partnerships once they're real.",
  },
  {
    icon: "Compass",
    title: "Earned Standing",
    description:
      "Reputation you can't fake. Members earn standing through documented outcomes, so an Astrada introduction always means something.",
  },
];

/* ── Who Astrada is for (archetypes, not real people) ───────── */
export const archetypes: Archetype[] = [
  {
    icon: "Rocket",
    title: "The early operator",
    description:
      "You've shipped something real and have customers paying for it. You're past the idea stage and into the hard, unglamorous middle.",
  },
  {
    icon: "TrendingUp",
    title: "The scaler",
    description:
      "You've found product-market fit and you're growing a team. The problems are bigger now, and the people who can relate are fewer.",
  },
  {
    icon: "Anchor",
    title: "The repeat founder",
    description:
      "You've built before — maybe sold, maybe not — and you're doing it again with scar tissue and conviction.",
  },
];

/* ── Membership levels (earned, not bought) ─────────────────── */
export const levels: LevelDef[] = [
  { level: 1, name: "Founder", requirement: "A member with a live, revenue-generating company." },
  { level: 2, name: "Operator", requirement: "Meaningful revenue, or a priced funding round." },
  { level: 3, name: "Builder", requirement: "Significant scale — revenue, a notable exit, or a real team." },
  { level: 4, name: "Architect", requirement: "Category-defining traction or a significant exit." },
  { level: 5, name: "Luminary", requirement: "Generational outcomes. By member nomination only." },
];

/* ── Sample members (illustrative — labeled as such in the app) ─ */
export const members: Member[] = [
  {
    id: "maya-okonkwo",
    name: "Maya Okonkwo",
    title: "Co-founder & CEO",
    company: "Relm Health",
    city: "London",
    country: "UK",
    level: 4,
    industry: "Healthtech",
    bio: "Building the operating system for community health clinics across Europe. Previously led product at a fintech.",
    building: "Expanding Relm to its next set of clinics.",
    highlight: "Scaled to eight figures in annual revenue.",
    tags: ["Healthtech", "B2B SaaS", "Europe"],
    joinedYear: 2026,
  },
  {
    id: "daniel-reyes",
    name: "Daniel Reyes",
    title: "Founder",
    company: "Kessler Logistics",
    city: "Austin",
    country: "USA",
    level: 3,
    industry: "Logistics",
    bio: "Automating middle-mile freight for mid-market manufacturers. Bootstrapped to profitability.",
    building: "Launching an autonomous dispatch product.",
    highlight: "Bootstrapped to profitability with no outside capital.",
    tags: ["Logistics", "Bootstrapped", "AI"],
    joinedYear: 2026,
  },
  {
    id: "priya-nair",
    name: "Priya Nair",
    title: "Founder & CEO",
    company: "Northwind AI",
    city: "San Francisco",
    country: "USA",
    level: 4,
    industry: "Artificial Intelligence",
    bio: "Applied research lab turning frontier models into reliable enterprise agents.",
    building: "An agent platform for regulated industries.",
    highlight: "Raised a Series B led by tier-one funds.",
    tags: ["AI", "Enterprise", "Deep Tech"],
    joinedYear: 2026,
  },
  {
    id: "tobias-lind",
    name: "Tobias Lind",
    title: "Co-founder",
    company: "Vantage Robotics",
    city: "Berlin",
    country: "Germany",
    level: 3,
    industry: "Robotics",
    bio: "Warehouse robotics for European e-commerce. Mechanical engineer turned operator.",
    building: "Rolling out a new picking arm across fulfilment centers.",
    highlight: "Closed a Series B at a strong valuation.",
    tags: ["Robotics", "Hardware", "Logistics"],
    joinedYear: 2026,
  },
  {
    id: "amara-bello",
    name: "Amara Bello",
    title: "Founder & CEO",
    company: "Sable Finance",
    city: "Lagos",
    country: "Nigeria",
    level: 4,
    industry: "Fintech",
    bio: "Cross-border payments rails for African SMEs. Ex-central bank economist.",
    building: "Opening corridors into new markets.",
    highlight: "Processed over a billion dollars in volume.",
    tags: ["Fintech", "Payments", "Africa"],
    joinedYear: 2026,
  },
  {
    id: "ethan-park",
    name: "Ethan Park",
    title: "Founder",
    company: "Loomcraft",
    city: "Seoul",
    country: "South Korea",
    level: 2,
    industry: "Consumer",
    bio: "Direct-to-consumer technical apparel built around a proprietary fabric.",
    building: "Opening first flagship retail.",
    highlight: "Profitable within eighteen months.",
    tags: ["Consumer", "DTC", "Retail"],
    joinedYear: 2026,
  },
  {
    id: "sofia-marchetti",
    name: "Sofia Marchetti",
    title: "Co-founder & CTO",
    company: "Tessera Bio",
    city: "Boston",
    country: "USA",
    level: 3,
    industry: "Biotech",
    bio: "Computational biology platform shortening drug discovery cycles.",
    building: "Moving molecules toward preclinical trials.",
    highlight: "Partnered with major pharma companies.",
    tags: ["Biotech", "Deep Tech", "Healthcare"],
    joinedYear: 2026,
  },
  {
    id: "marcus-hale",
    name: "Marcus Hale",
    title: "Founder & CEO",
    company: "Forge Studios",
    city: "Los Angeles",
    country: "USA",
    level: 5,
    industry: "Media",
    bio: "Built and sold two studios; now backing the next generation of creator-led brands.",
    building: "A holding company for creator commerce.",
    highlight: "Two exits behind him.",
    tags: ["Media", "Creator Economy", "Investor"],
    joinedYear: 2026,
  },
  {
    id: "yuki-tanaka",
    name: "Yuki Tanaka",
    title: "Founder",
    company: "Plinth",
    city: "Singapore",
    country: "Singapore",
    level: 3,
    industry: "Developer Tools",
    bio: "Infrastructure for real-time data pipelines. Open-source first.",
    building: "Launching a managed cloud for the open-source core.",
    highlight: "A thriving open-source project with paying teams.",
    tags: ["Dev Tools", "Open Source", "Infra"],
    joinedYear: 2026,
  },
  {
    id: "nadia-haddad",
    name: "Nadia Haddad",
    title: "Co-founder & CEO",
    company: "Cedar & Co",
    city: "Dubai",
    country: "UAE",
    level: 2,
    industry: "Marketplace",
    bio: "A vetted marketplace connecting interior designers with manufacturers.",
    building: "Expanding the supply network across the Gulf.",
    highlight: "Strong early marketplace traction.",
    tags: ["Marketplace", "Design", "MENA"],
    joinedYear: 2026,
  },
  {
    id: "liam-osullivan",
    name: "Liam O'Sullivan",
    title: "Founder",
    company: "Halyard",
    city: "Dublin",
    country: "Ireland",
    level: 2,
    industry: "Climate",
    bio: "Carbon accounting for the maritime shipping industry.",
    building: "Onboarding large fleets.",
    highlight: "Backed by a leading climate fund.",
    tags: ["Climate", "B2B SaaS", "Maritime"],
    joinedYear: 2026,
  },
  {
    id: "isabella-cruz",
    name: "Isabella Cruz",
    title: "Founder & CEO",
    company: "Lumen Education",
    city: "Mexico City",
    country: "Mexico",
    level: 3,
    industry: "Edtech",
    bio: "Vocational upskilling platform for Latin America's workforce.",
    building: "Government partnerships across the region.",
    highlight: "Over a million learners.",
    tags: ["Edtech", "LatAm", "Marketplace"],
    joinedYear: 2026,
  },
  {
    id: "arjun-mehta",
    name: "Arjun Mehta",
    title: "Co-founder",
    company: "Stride Capital Tech",
    city: "Bangalore",
    country: "India",
    level: 3,
    industry: "Fintech",
    bio: "Embedded lending infrastructure for Indian commerce platforms.",
    building: "A new underwriting engine on alternative data.",
    highlight: "Significant loan volume disbursed.",
    tags: ["Fintech", "Lending", "India"],
    joinedYear: 2026,
  },
  {
    id: "clara-jensen",
    name: "Clara Jensen",
    title: "Founder & CEO",
    company: "Atrium Robotics",
    city: "Copenhagen",
    country: "Denmark",
    level: 2,
    industry: "Robotics",
    bio: "Autonomous cleaning robots for commercial real estate.",
    building: "Pilots with major property managers.",
    highlight: "Profitable within thirty months.",
    tags: ["Robotics", "PropTech", "Hardware"],
    joinedYear: 2026,
  },
  {
    id: "samuel-adeyemi",
    name: "Samuel Adeyemi",
    title: "Founder",
    company: "Verdant",
    city: "Nairobi",
    country: "Kenya",
    level: 2,
    industry: "Agtech",
    bio: "Satellite-driven crop insurance for smallholder farmers.",
    building: "Insuring more acres each season.",
    highlight: "Reached farmers across East Africa.",
    tags: ["Agtech", "Insurance", "Africa"],
    joinedYear: 2026,
  },
  {
    id: "hannah-cohen",
    name: "Hannah Cohen",
    title: "Co-founder & CEO",
    company: "Beacon Security",
    city: "Tel Aviv",
    country: "Israel",
    level: 4,
    industry: "Cybersecurity",
    bio: "Identity security platform for cloud-native enterprises. Ex-intelligence.",
    building: "Defending the identity layer for large customers.",
    highlight: "Crossed eight figures in annual revenue.",
    tags: ["Security", "Enterprise", "B2B SaaS"],
    joinedYear: 2026,
  },
  {
    id: "noah-becker",
    name: "Noah Becker",
    title: "Founder & CEO",
    company: "Atlas Freight",
    city: "Chicago",
    country: "USA",
    level: 3,
    industry: "Logistics",
    bio: "A modern freight brokerage powered by automation.",
    building: "Scaling brokerage automation to new lanes.",
    highlight: "Large volume of freight under management.",
    tags: ["Logistics", "Marketplace", "Automation"],
    joinedYear: 2026,
  },
  {
    id: "valentina-rossi",
    name: "Valentina Rossi",
    title: "Founder",
    company: "Maison Vera",
    city: "Milan",
    country: "Italy",
    level: 3,
    industry: "Consumer",
    bio: "Luxury skincare built on clinical-grade actives and sustainable sourcing.",
    building: "Entering new markets through premium retail.",
    highlight: "Healthy revenue with strong margins.",
    tags: ["Consumer", "Beauty", "DTC"],
    joinedYear: 2026,
  },
];

/* ── Sample events (illustrative — labeled in the app) ──────── */
export const events: ClubEvent[] = [
  {
    id: "sf-dinner-jul",
    title: "Founding Dinner — San Francisco",
    type: "dinner",
    date: "2026-07-09",
    time: "7:00 PM",
    city: "San Francisco",
    venue: "Private room, Nob Hill",
    host: "Priya Nair",
    capacity: 12,
    spotsLeft: 5,
    description:
      "One of the first Astrada dinners. A small table of founding members — off the record, no agenda, no pitching.",
  },
  {
    id: "ldn-dinner-jul",
    title: "Founding Dinner — London",
    type: "dinner",
    date: "2026-07-15",
    time: "7:30 PM",
    city: "London",
    venue: "Members' room, Shoreditch",
    host: "Maya Okonkwo",
    capacity: 10,
    spotsLeft: 4,
    description:
      "An intimate evening for founding members in London — candid conversation about what's actually hard right now.",
  },
  {
    id: "nyc-run-jul",
    title: "Morning Run — New York",
    type: "run",
    date: "2026-07-06",
    time: "6:30 AM",
    city: "New York",
    venue: "Bethesda Terrace, Central Park",
    host: "Noah Becker",
    capacity: 20,
    spotsLeft: 12,
    description:
      "An easy loop through the park before the city wakes up. All paces welcome — the best ideas arrive around mile six.",
  },
  {
    id: "berlin-dinner-jul",
    title: "Founding Dinner — Berlin",
    type: "dinner",
    date: "2026-07-22",
    time: "7:30 PM",
    city: "Berlin",
    venue: "Private kitchen, Mitte",
    host: "Tobias Lind",
    capacity: 10,
    spotsLeft: 6,
    description:
      "A long European dinner with founders building hard things — hardware, robotics, deep tech.",
  },
  {
    id: "fundraising-workshop",
    title: "Workshop — Fundraising in a Hard Market",
    type: "workshop",
    date: "2026-07-29",
    time: "4:00 PM",
    city: "Virtual",
    venue: "Members-only livestream",
    host: "Hannah Cohen",
    capacity: 100,
    spotsLeft: 64,
    description:
      "A tactical, no-fluff session on running a tight raise — real decks, real terms, live Q&A. Recording shared with members after.",
  },
  {
    id: "austin-social-aug",
    title: "Members' Social — Austin",
    type: "social",
    date: "2026-08-12",
    time: "6:00 PM",
    city: "Austin",
    venue: "Rooftop, East Austin",
    host: "Daniel Reyes",
    capacity: 40,
    spotsLeft: 22,
    description:
      "A relaxed rooftop evening — bring a founder friend who might be a fit for the founding circle.",
  },
];

/* ── Perks we're lining up (no fake partners, nothing live yet) ─ */
export const perks: Perk[] = [
  {
    id: "cloud",
    title: "Cloud infrastructure credits",
    category: "Infrastructure",
    status: "Lining up",
    description: "Compute, storage, and database credits with leading cloud providers for early-stage teams.",
    monogram: "☁",
  },
  {
    id: "payments",
    title: "Payments & billing",
    category: "Payments",
    status: "Lining up",
    description: "Reduced processing rates and priority onboarding with modern payments platforms.",
    monogram: "₽",
  },
  {
    id: "design",
    title: "Design & prototyping tools",
    category: "Design",
    status: "Lining up",
    description: "Extended trials and member rates on the design and prototyping tools founders rely on.",
    monogram: "✦",
  },
  {
    id: "payroll",
    title: "Global payroll & hiring",
    category: "HR & Payroll",
    status: "Lining up",
    description: "Member pricing on platforms for hiring and paying a distributed team.",
    monogram: "⊞",
  },
  {
    id: "banking",
    title: "Business banking",
    category: "Banking",
    status: "Lining up",
    description: "Fast-tracked onboarding and founder perks with startup-friendly banking partners.",
    monogram: "$",
  },
  {
    id: "equity",
    title: "Equity & cap table",
    category: "Legal & Equity",
    status: "Lining up",
    description: "Member rates on cap-table management and staying fundraise-ready.",
    monogram: "%",
  },
  {
    id: "ai",
    title: "AI model credits",
    category: "AI",
    status: "Lining up",
    description: "Credits across frontier and open models to build AI into your product.",
    monogram: "◆",
  },
  {
    id: "travel",
    title: "Travel & stays",
    category: "Travel",
    status: "Lining up",
    description: "Member rates on stays and lounge access for founders who live on the road.",
    monogram: "✈",
  },
  {
    id: "productivity",
    title: "Productivity suite",
    category: "Productivity",
    status: "Lining up",
    description: "Extended access and member rates on the docs, email, and project tools teams run on.",
    monogram: "▤",
  },
];

/* ── FAQ — honest about being new ───────────────────────────── */
export const faqs: FaqItem[] = [
  {
    q: "Is Astrada actually up and running?",
    a: "Astrada is brand new — we're forming the founding circle right now. We'd rather be honest about that than fake a community that doesn't exist yet. Founding members shape what this becomes, from the first dinners to the perks we line up.",
  },
  {
    q: "Who is Astrada for?",
    a: "Founders who are actively building a company with real traction — paying customers, funding, a team, or a meaningful exit behind them. We're industry-agnostic, but this isn't for aspiring founders, students, or service providers looking for clients.",
  },
  {
    q: "How do I join?",
    a: "Join directly through Whop — pick monthly or annual, check out securely (right here on the site), and you're in. Then sign in with Whop to enter the members' area.",
  },
  {
    q: "What does membership cost?",
    a: "$49 per month, or $400 per year — annual saves you two months. Membership runs on Whop and you can cancel anytime.",
  },
  {
    q: "What are member levels?",
    a: "Levels are earned, not bought. Every member starts as a Founder and progresses through documented outcomes — revenue, funding, exits. There's no faking your way up, which is what gives an Astrada introduction its weight.",
  },
  {
    q: "Why join now instead of waiting?",
    a: "Because the founding circle is small by design, and the earliest members have the most say in what Astrada becomes — and the most to gain from being known here first.",
  },
];
